### ISSUE TITLE
[BUG] Steward Wallet Page - Displaying inaccurate amount paid to Steward

### ISSUE THREAD

**Issue by decentralauren** [GoodDollar/GoodCollective#128] opened 2024-01-30 14:28 UTC
Amount received by steward is incorrect:

![Screenshot 2024-01-30 at 10 18 03 AM](https://github.com/GoodDollar/GoodCollective/assets/149098646/d87933c3-dc18-4d27-8c5c-43e80d1082f5)

**Comment by krisbitney** [comment] 2024-01-30 16:47
@decentralauren Could you please tell me what the correct value is?

@sirpy Could you please clarify how rewards should be calculated?

This is the current logic. What about this is incorrect?
```ts
    const totalReward = rewardPerContributor.times(eventQuantity);

    // update StewardCollective
    let stewardCollective = StewardCollective.load(stewardCollectiveId);
    if (stewardCollective === null) {
      stewardCollective = new StewardCollective(stewardCollectiveId);
      stewardCollective.actions = 0;
      stewardCollective.totalEarned = BigInt.fromI32(0);
    }
    stewardCollective.actions = stewardCollective.actions + 1;
    stewardCollective.totalEarned = stewardCollective.totalEarned.plus(totalReward);
    ```

**Comment by decentralauren** [comment] 2024-01-31 18:08
cc @L03TJ3 in case you can help.

@krisbitney the "total paid out" amount in the Collective page is the summary of the value described above across all stewards who have been paid. The Total Paid Out for this pool is 24,001 G$.

**Comment by decentralauren** [comment] 2024-01-31 23:15
IE the total paid out to this steward should be 24,001 less any amounts paid to other stewards.

**Comment by krisbitney** [comment] 2024-02-01 06:38
> cc @L03TJ3 in case you can help.
> 
> @krisbitney the "total paid out" amount in the Collective page is the summary of the value described above across all stewards who have been paid. The Total Paid Out for this pool is 24,001 G$.

Are you sure the Total Paid Out value of $24,001 is correct? is it possible that the Steward value is correct and the Total Paid Out value is not? I ask because I found a discrepancy and it actually looks like the Steward value might be correct and the Total Paid Out value might not be. I say that just based on which equation looks correct, not based on the results of the calculations.

**Comment by sirpy** [comment] 2024-02-01 08:24
@krisbitney 
Looking at the on-chain data, the steward has received 24k G$s.
There's no need to multiply by quantity that's the cause of the error. the rewardpercontributer in the event is the final amount.

**Comment by krisbitney** [comment] 2024-02-01 08:31
> @krisbitney Looking at the on-chain data, the steward has received 24k G$s. There's no need to multiply by quantity that's the cause of the error. the rewardpercontributer in the event is the final amount.

Thanks!

**Comment by krisbitney** [comment] 2024-02-01 12:45
This is fixed in https://github.com/GoodDollar/GoodCollective/pull/144

**Comment by vldkhh** [comment] 2024-02-01 17:41
verified

**Closed by vldkhh** 2024-02-01 17:41 UTC
Labels: bug, P1 - High
