### ISSUE TITLE
[Improvements] Superfluid Link should open in new page

### ISSUE THREAD

**Issue by vldkhh** [GoodDollar/GoodCollective#99] opened 2024-01-12 15:13 UTC
![image](https://github.com/GoodDollar/GoodCollective/assets/6606028/eb5109c6-df9d-4b01-8a94-cec3306d8fe5)

**Comment by krisbitney** [comment] 2024-01-13 15:11
The image isn't displaying and i'm not sure what this issue means. Could you clarify?

**Comment by krisbitney** [comment] 2024-01-24 13:31
Okay, I understand. That will be out of scope for the MVP because it's a little bit complex to handle in React Native. 

It is complex because React Native is made to work with Web, Android, iOS. Since Android and iOS apps don't have the intrinsic concept of tabs, React Native doesn't support opening a link in a new tab/window out of the box.

**Comment by vldkhh** [comment] 2024-01-24 14:12
@L03TJ3

**Comment by L03TJ3** [comment] 2024-01-24 14:57
@krisbitney you can use the Link component from the native-base library

Example implementation here: https://github.com/GoodDollar/GoodWeb3-Mono/blob/6d4b2d1b9e4335cdeed84b896c2dd90676777e33/packages/good-design/src/core/web3/modals/RedirectModal.tsx#L17

**Comment by L03TJ3** [comment] 2024-01-24 15:03
@krisbitney sorry to ping you twice. Misclicked.

You can use the Link component from the native-base library for this.

Reference: https://docs.nativebase.io/link

Example implementation here: https://github.com/GoodDollar/GoodWeb3-Mono/blob/6d4b2d1b9e4335cdeed84b896c2dd90676777e33/packages/good-design/src/core/web3/modals/RedirectModal.tsx#L17

**Comment by krisbitney** [comment] 2024-01-24 15:26
It is fixed in this PR: https://github.com/GoodDollar/GoodCollective/pull/117

Thanks @L03TJ3 . That component was already being used, but I realized there was a bug due to it being wrapped by a `text` element instead of the other way around. (i.e. it was `<text><Link></Link></text>` instead of the text being nested within the Link). Your example helped me see the issue.

**Comment by L03TJ3** [comment] 2024-01-24 15:33
Ah yeah now I see that link is used everywhere already :nerd_face: 
but ok nice!
are you going to use that pr for other issues as well? or can I merge
@krisbitney

**Comment by krisbitney** [comment] 2024-01-24 15:36
> Ah yeah now I see that link is used everywhere already 🤓 but ok nice! are you going to use that pr for other issues as well? or can I merge @krisbitney

You can merge if you'd like

**Comment by L03TJ3** [comment] 2024-01-24 15:38
ye just cleaning up the board a bit.
Confirmed this is working so closing

**Closed by L03TJ3** 2024-01-24 15:38 UTC
Labels: P3 - Low
